### ISSUE TITLE
[relm-gen-widget] too few type parameters provided

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#101]
Hello,

A new release, new errors I don’t understand :smile: 

```
error[E0089]: too few type parameters provided: expected 2 type parameters, found 1 type parameter
  --> src/done.rs:37:16                                           
   |                                        
37 |         #[name="tasks"]                          
   |                ^^^^^^^ expected 2 type parameters  
```

https://github.com/sanpii/effitask/blob/relm-0.14/src/done.rs#L37

I fixed some compilation errors on the [relm-0.14 branch](https://github.com/sanpii/effitask/tree/relm-0.14).

**Comment by antoyo** [comment]
There's a bug in the code generator.
I'll add a test to it and fix it.
Thanks for reporting it.

**Comment by sanpii** [comment]
Thank you :)
