### ISSUE TITLE
libgtkflow with relm?

### ISSUE THREAD

**Issue by lf94** [antoyo/relm#113]
https://github.com/grindhold/libgtkflow would be *really* nice to use with relm. How can I? I will do whatever work necessary but I don't know where to start.

**Comment by antoyo** [comment]
The first thing you need to do is to generate a sys and a wrapper binding.
For doing that, you will need to find the `GtkFlow-0.2.gir` file.
Then, you need to use [`gir`](https://github.com/gtk-rs/gir) to generate the bindings.
When you have the bindings, you can use it in `relm` normally.
Look at the [`webkit2gtk` example](https://github.com/antoyo/relm/tree/master/examples/webkit-test) to see an example done with another library.
The only thing worth knowing is that you need to use the prefix of your library (`webkit2gtk` in this example) in your [view](https://github.com/antoyo/relm/blob/master/examples/webkit-test/src/main.rs#L72).
Hope it's clear.

**Comment by lf94** [comment]
Thank you. I guess I'll be trying something new tonight! :)

**Comment by lf94** [comment]
I'm getting this when trying to generate the FFI with gir:

`GirXml: ../gir-files/GtkFlow-0.2.gir:20:5: Missing c:type attribute`

Any tips?

**Comment by lf94** [comment]
For others who try this: `GtkFlow-0.2.gir` when generated with `gir`, has this in its file for return types:

`<type name="none"/>`

This should be corrected to:

`<type name="none" c:type="void"/>`

**Comment by lf94** [comment]
Final blocker: `thread 'main' panicked at 'Incomplete library, unresolved: ["GtkFlow.Node", "GFlow.Dock", "GFlow.Node"]', src/library_postprocessing.rs:55:13`

**Comment by lf94** [comment]
GtkFlow defines `libgtkflow/node.vala` main class as private, causing `GtkFlow.Node` to be not output in the `.gir` file.

GFlow.Dock and GFlow.Node are defined in GFlow's gir file.

**Comment by lf94** [comment]
Adding them to the `ignore` property did not fix the problem. Neither did adding the external_library option with "GFlow" in the list.

**Comment by lf94** [comment]
@antoyo heeeelp D: I'm so close to finishing this. Just those 2 GFlow symbols are unresolved.

**Comment by GuillaumeGomez** [comment]
@lf94: Sounds like GFlow is completely missing from your gir file. Generally what we do is setting its generation as "manual" and then you implement it by hand. Not very funny but at least you'll be able to end your binding generation.

**Comment by lf94** [comment]
@GuillaumeGomez I have a GFlow gir file as well, that I added to `external_libs` but gir didn't pick it up? And in `manual` I added those two references but it still said they were missing...

If I have the gir file, how do I get gir to detect it?

**Comment by GuillaumeGomez** [comment]
It's referenced for the gir file normally. For example, `glib` is included as follows in gtk gir file:

```xml
<repository xmlns="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspect\
ion/c/1.0" xmlns:glib="http://www.gtk.org/introspection/glib/1.0" version="1.2">
```

And you have everything needed inside directly.

**Comment by lf94** [comment]
Err, are you sure that's just not some schema (sorry if I get the terminology wrong, it has been 10+ years I have even seen XML)? The content right below that line seems like something I'd possibly use:

```
  <include name="Atk" version="1.0"/>
  <include name="Gdk" version="3.0"/>
  <include name="xlib" version="2.0"/>
```

**Comment by GuillaumeGomez** [comment]
I think you're right. Sorry but I didn't much on this part in gir. Do you mind opening a PR on the [gir](https://github.com/gtk-rs/gir) repository directly please?

**Comment by GuillaumeGomez** [comment]
Sure!

**Comment by lf94** [comment]
I got some warnings, but adding `<include name="GFlow" version="0.2">` worked!

**Comment by GuillaumeGomez** [comment]
Then your gir file was just incomplete (which is, unfortunately, quite common...).

**Comment by grindhold** [comment]
i have pushed a commit to https://notabug.org/grindhold/libgtkflow master that makes `GtkFlow.Node` public and adds a doc-comment that tells users not to use the class in applilcation code.  Please try it and tell me wheter it helped your case. Either here or at the related issue: https://notabug.org/grindhold/libgtkflow/issues/34
