### ISSUE TITLE
add support for submenu to view!

### ISSUE THREAD

**Issue by fneddy** [antoyo/relm#115]
currently it is not possible to add a submenu to a menuitem within a `view!`
you need to create it manualy in init_view [buttons-test.rs#L124](https://github.com/antoyo/relm/blob/master/tests/buttons-test.rs#L124).

maybe add a `#[submenu]` attribute that will change from `ContainerExt::add` to `MenuItemExt::set_submenu`:

```rust
 gtk::MenuBar{
    gtk::MenuItem{
        label:"_File",
        use_underline: true,
        
        #[submenu]
        gtk::Menu{
            gtk::ImageMenuItem{
                label: "gtk-save",
                use_underline: true,
            },
        },
    },
},
```

**Comment by antoyo** [comment]
Dupplicate of #54.
