### ISSUE TITLE
Syntax to disable automatic show() for root widget

### ISSUE THREAD

**Issue by myfreeweb** [antoyo/relm#121]
I'd like to have some syntax like

```rust
view! {
    #[no_auto_show]
    gtk::Window { ... }
}
```

to prevent the `show()` from being generated.

**Comment by antoyo** [comment]
What's your use case for that?
I think that when I'll fix issue #42, it will be possible to add a widget after the first one, and this second widget won't be shown.
Would that be enough for you?

**Comment by myfreeweb** [comment]
An app launcher window (like the Start menu in Windows) that's initially hidden, its visibility is toggled from outside.
Second widget won't be enough, it has to be the root.

I'm currently just hiding it after creation, that's not too bad, but would be ideal to get rid of that inefficiency :)

**Comment by antoyo** [comment]
Oh, in that case, you can only do:
```rust
view! {
    gtk::Window {
        visible: false,
    }
}
```
This feature already exists.

**Comment by myfreeweb** [comment]
Oh, that does work. I thought it would be shown anyway by the generated code. Thanks!

**Comment by antoyo** [comment]
No, the `visible` property is a special case and is applied last, i.e. after the widgets are shown.
