### ISSUE TITLE
How to use gtk::Frame

### ISSUE THREAD

**Issue by Yatekii** [antoyo/relm#126]
Hi!

I tried to use `gtk::Frame`. But when I tried the following

```rust
gtk::Frame {
    label_widget: gtk::Label {
        text: "KEK"
    }
}
```

it tells me that text is not an attribute for `gtk::Label` which kind of makes sense, but I don't know how to help myself :S Same goes for the case when I try to assign a Label ... it will always complain about a typemissmatch (Option<&String> vs Option<&str> which is weird.

Best,
Yatekii

**Comment by antoyo** [comment]
On the right side of `:`, you need to use normal Rust code.
Hence, you will need to use:
```rust
gtk::Frame {
    label_widget: &gtk::Label::new("KEK"),
}
```
I'm not sure what would be appropriate for this case.
Should we allow using the same syntax?

**Comment by Yatekii** [comment]
Ok that makes sense! Sadly this will only display a grey bar, even when I add a content string. I will have a look at thr expanded code when I get home because I don't think this is necessairily a relm but quite possibly a gtk-rs issue.

The problem I see with the entirety of this is that the reactive approach does not seem to work on multiple hierarchical levels here. Can you confirm this? :)

The

**Comment by antoyo** [comment]
Yeah.
When I'll fix [this issue](https://github.com/antoyo/relm/issues/42), it will probably be possible to write:
```rust
gtk::Frame {
    label_widget: &self.label,
},
#[name="label"]
gtk::Label {
    text: &self.model.label.to_string(),
}
```
Which will enable the reactive approach for this case.
Would that be good enough?

**Comment by Yatekii** [comment]
Yeah I guess that would be nice. Way nicer would be a nested approach, but idk how hard this is.
I could do some work too, but I have no idea if I have enough knowledge, exspecially with the macro parts.
Are you around on IRC or similar?

**Comment by antoyo** [comment]
I am on irc.gnome.org#rust and irc.mozilla.org#gtk-rs most of time.

For the nested approach, I'm not sure what the syntax would like. How can I know if it's going to be a normal struct or a view widget?

**Comment by Yatekii** [comment]
> For the nested approach, I'm not sure what the syntax would look like. How can I know if it's going to be a normal struct or a view widget?

Maybe using a second view!{}? Like so:

```
view!(gtk::Frame{
    label_widget: !view(gtk::Label{
        text: &self.model.kek
    }),
    label: &self.model.top
})
```

**Comment by antoyo** [comment]
That is now possible. See this [example](https://github.com/antoyo/relm/blob/master/relm-examples/examples/nested-view-attribute.rs#L181-L192).
