### ISSUE TITLE
Setting WindowType with the view macro

### ISSUE THREAD

**Issue by henriklaxhuber** [antoyo/relm#128]
In GTK+, the window type must be set in the window constructor and cannot be changed thereafter (there is no `set_type` method). While I am new to relm, I understand that this makes it impossible to use the view macro when creating a window that is not a toplevel window, such as a popup.

A possible solution would be to perhaps introduce a syntax for passing constructor paramters with the view macro. I think something like the following would make sense:

```rust
view! {
    gtk::Window(gtk::WindowType::Popup) {
        // ...
    }
}
```

i.e. adding constructor parameters for GTK+ widgets within parentheses. Such a feature addition would be compatible with the current version of relm, as the parentheses may be omitted when no constructor parameters are passed.

**Comment by antoyo** [comment]
That is already implemented and with exactly the same syntax you thought :) .
[Here's an example.](https://github.com/antoyo/relm/blob/541e1dcac24101abbae39cbaa46456ea12c0b985/tests/buttons-child-attribute.rs#L76).
