### ISSUE TITLE
gdk interface

### ISSUE THREAD

**Issue by jpercyasnet** [antoyo/relm#136]
I am trying to use gtkIconView, but it requires pixbuf items and I tried everything to setup a ListStore and failing at loading the ListStore with pixbuf and text. Is it possible to use IconView and if so, can you provide an example. I am trying to convert my python qt programs to rust gtk using relm.

**Comment by antoyo** [comment]
So, for now, we cannot integerate a [GTK+ model with a relm model](https://github.com/antoyo/relm/issues/17), but you can create your `IconView` widget normally (like the `TreeView` [here](https://github.com/antoyo/mg/blob/master/src/completion/completion_view.rs#L138)) and [call `set_model()`](https://github.com/antoyo/mg/blob/master/src/completion/completion_view.rs#L188) on it, possibly in the [`init_view()` method](https://github.com/antoyo/mg/blob/master/src/completion/completion_view.rs#L91) which gets called after the view is initialized.

**Comment by antoyo** [comment]
Please reopen if you still need help.
