### ISSUE TITLE
relm_core::Sender is not publicly reexported by the relm crate

### ISSUE THREAD

**Issue by netvl** [antoyo/relm#138]
The `relm_core::Sender` type, unlike `relm_core::Channel`, is not publicly reexported by the `relm` crate, making it not possible to store it inside a structure for further use. Is this intentional for some reason?

**Comment by antoyo** [comment]
Fixed [here](https://github.com/antoyo/relm/commit/b6029c1318279ac6877177742ae5ce3870b7b257).
