### ISSUE TITLE
relm_core::Sender is not Clone if its type parameter is not Clone

### ISSUE THREAD

**Issue by netvl** [antoyo/relm#139]
As far as I remember, `#[derive(Clone)]` is kinda dumb - it will only derive `Clone` if all type arguments of the type are `Clone`. However, for types like `Sender` it does not matter whether the type they are parametrized by is `Clone`, they are just intrinsically cloneable. Therefore, I think, it is necessary to explicitly implement `Clone` - otherwise it won't be easily possible to clone the `Sender` end of the channel to send it to several threads.

**Comment by sunjay** [comment]
It looks like Sender only has one field and that field has an mpsc::Sender in it. mpsc::Sender implements clone regardless of its inner type, so Sender should also do that as well. Did you see something different? Also, were you unable to clone it when you tried?

**Comment by netvl** [comment]
@sunjay 

>  Also, were you unable to clone it when you tried?

Exactly.

From `#[derive(Clone)]` perspective, it does not matter that the internal type implements `Clone` regardless of type parameter; it still would require all type parameters to be `Clone`:

```rust
#[derive(Clone)]
struct Something<T> {
    ...
}

// expands to

impl<T: Clone> Clone for Something<T> {
    ...
}
```

It is necessary to explicitly write `impl<T> Clone for Something<T>` in order to avoid this unnecessary bound on the type parameter.
