### ISSUE TITLE
How and whether to use gtk::Application

### ISSUE THREAD

**Issue by njam** [antoyo/relm#141]
I'm a newcomer to GTK. I can see many applications and guides using `GtkApplication`, but cannot find any reference to it in _relm_.

I've tried to create an application that can listen for the "open" event for opening files in the _primary_ instance when passing a filename on the command line.

Is _relm_ not using `gtk::Application` on purpose?

Do you think it's a valid approach to create a `gtk::Application` instance, and then on "activate" or "open"  create a new `relm::Component` with `relm::init()`?

Roughly the idea is:
```rust
fn main() {
    let gtk_app = gtk::Application::new(appid, gio::ApplicationFlags::HANDLES_OPEN).unwrap();
    
    gtk_app.connect_open(move |gtk_app, files, _| {
        for file in files {
            println!("DEBUG: open new window for file {:?}", file.get_path().unwrap());
            let component: relm::Component<MyWin> = relm::init(()).unwrap();
            let window: &gtk::Window = component.widget();
            window.set_application(&gtk_app);
        }
    });
    
    let args: Vec<String> = std::env::args().collect();
    gtk_app.run(&args[..]);
}
```
(full example: https://gist.github.com/njam/1b36ba58d7401865dabd302fc37543da)

**Comment by antoyo** [comment]
That seems perfectly valid.
There is no reason not to use `gtk::Application`.

**Comment by njam** [comment]
Great, thanks for the feedback! I will continue like this then.
