### ISSUE TITLE
Updating model and view from different methods

### ISSUE THREAD

**Issue by kl** [antoyo/relm#143]
Looking at some examples I noticed that the code that update() method in Win trait is updating both the model and the GTK+ widgets. For example (from examples/buttons.rs):

```rust
    fn update(&mut self, event: Msg) {
        let label = &self.widgets.counter_label;

        match event {
            Msg::Decrement => {
                self.model.counter -= 1;
                // Manually update the view.
                label.set_text(&self.model.counter.to_string());
            },
            Msg::Increment => {
                self.model.counter += 1;
                label.set_text(&self.model.counter.to_string());
            },
            Msg::Quit => gtk::main_quit(),
        }
    }
```

As I understand the Elm architecture the update layer should update the model based on the events that are generated and the view layer should then take the updated model and render a new view. As the code is now the update layer both updates the model and renders the new view. I think that the separation of concerns would be better if it was possible to update the view from the Widget trait instead. This could probably be implemented in a backwards-compatible way by adding a new method update() to the Widget trait and then have the framework call that method after update() in Win is called. What are your thoughts on this?

**Comment by antoyo** [comment]
Well, actually the procedural macro does something similar.
Look at [this example](https://github.com/antoyo/relm/issues/143).

**Comment by antoyo** [comment]
Please reopen if you need more explanations.
