### ISSUE TITLE
README is rendered incorrectly on crates.io

### ISSUE THREAD

**Issue by berkus** [antoyo/relm#144]
Look at https://crates.io/crates/relm

Yes, crates doesn't support rendering adoc documents that's why it looks so bad.

Suggestion: convert to markdown? I could help if you don't want to spend time on this.

**Comment by antoyo** [comment]
[That's an issue in crates.io.](https://github.com/rust-lang/crates.io/issues/995)

Sorry, but I'm not switching to Markdown.
If you want this to be fixed, please open a new issue in the crates.io issue tracker: maybe they'll understand what is needed this time.

**Comment by berkus** [comment]
Why do you want to use adoc over md?
