### ISSUE TITLE
GtkStackSwitcher and GtkStack

### ISSUE THREAD

**Issue by sumnerevans** [antoyo/relm#150]
I am trying to create an application with a `GtkStackSwitcher` and a `GtkStack`. I have a few questions as to the best approach for doing this.

1. From the [GNOME documentation for `GtkStackSwitcher`](https://developer.gnome.org/gtk3/stable/GtkStackSwitcher.html), it appears that you can set a `GtkStack` for the switcher and it will automatically(?) populate the switcher with buttons. Is there a way to do this in Relm?

2. Since I could not figure out a way to do (1), I settled on the following structure:

        gtk::Window {
            gtk::Box {
                orientation: Vertical,

                gtk::HeaderBar {
                    gtk::StackSwitcher {
                        gtk::ToggleButton {
                            ... (button for Albums, Artists, Playlists, More)
                        },
                        ...
                    },
                },

                #[name="main_stack"]
                gtk::Stack {
                    visible_child_name: match self.model.active_tab {
                        Albums => "albums",
                        Artists => "artists",
                        Playlists => "playlists",
                        More => "more",
                    },

                    #[name="albums"]
                    gtk::Label {
                        label: "Albums",
                    },

                    #[name="artists"]
                    gtk::Label {
                        label: "Artists"
                    },

                    #[name="playlists"]
                    gtk::Label {
                        label: "Playlists"
                    },

                    #[name="more"]
                    gtk::Label {
                        label: "More"
                    },
                }
            },
            delete_event(_, _) => (Quit, Inhibit(false)),
        }

    The problem is that I get the following error when I run this code and change the `active_tab`:

        (.:3016): Gtk-WARNING **: 13:30:33.134: Child name 'artists' not found in GtkStack

    Am I using this incorrectly? What recommendations do you have for resolving this issue? Is there any prior-art that I can look at?

Thanks for your time!

**Comment by antoyo** [comment]
So, usually, you'd do something like this:
```rust
gtk::Window {
    gtk::Box {
        orientation: Vertical,
        #[name="stack_switcher"]
        gtk::StackSwitcher {
            stack: self.stack, // DOES NOT WORK.
        },
        #[name="stack"]
        gtk::Stack {
            #[name="inc_button"]
            gtk::Button {
                clicked => Increment,
                label: "+",

                // The following calls gtk::StackExt::set_child_title("Plus Button")
                child: {
                    title: "Plus Button",
                },
            },
            #[name="label"]
            gtk::Label {
                text: &self.model.counter.to_string(),

                child: {
                    title: "Label",
                },
            },
            #[name="dec_button"]
            gtk::Button {
                clicked => Decrement,
                label: "-",

                child: {
                    title: "Minus Button",
                },
            },
        }
    },
    delete_event(_, _) => (Quit, Inhibit(false)),
}
```
But the line with a comment does not work.
Notice how I set the title with the syntax for child properties.

Just remove this line and add this function to the relm widget:
```rust
    fn init_view(&mut self) {
        self.stack_switcher.set_stack(&self.stack);
    }
```

**Comment by sumnerevans** [comment]
Thank you! That worked. I am now trying to apply this to making the `StackSwitcher` the custom title for a header bar. My code currently is:

```
    fn init_view(&mut self) {
        // Main Stack Switcher
        let stack_switcher = gtk::StackSwitcher::new();
        stack_switcher.set_stack(&self.main_stack);
        self.main_header.set_custom_title(&stack_switcher);
    }
```

but when I run it, the switcher does not appear in the header bar.

Other things I've tried:

```
    fn init_view(&mut self) {
        // Main Stack Switcher
        self.stack_switcher.set_stack(&self.main_stack);
        self.main_header.set_custom_title(&self.stack_switcher);
    }
```
with the following in the `view!` widget:
```
                #[name="main_header"]
                gtk::HeaderBar {
                    show_close_button: true,
                    ...
                    #[name="stack_switcher"]
                    gtk::StackSwitcher {},
                    ...
                }
```

But that doesn't work because it does not allow resizing below a certain width (note the whitespace to the left of the switcher):

![2018-12-17-21 33 48](https://user-images.githubusercontent.com/16734772/50132493-9148a680-0244-11e9-9c95-61984dca4a6f.png)

Is there a cannonacle example of how to do this in Relm?

Thank you!

**Comment by antoyo** [comment]
It does not look like `gtk::HeaderBar` allows you to expand your widgets inside it (it's more of a GTK+ question, so I can be wrong though).
Also, for the first version to work, you'd need to call:
```rust
self.stack_switcher.show_all()
```

**Comment by sumnerevans** [comment]
Thank you @antoyo using `show_all()` works great!
