### ISSUE TITLE
Is there a way to create multiple instance of a widget in the `view!` macro?

### ISSUE THREAD

**Issue by ivanceras** [antoyo/relm#151]
Is it possible to enumate widgets in the `view!` macro like this?
```rust
view! {
    gtk::Window {
        gtk::Box {
        orientation: Vertical,
            {for (0..9).map(|i|{
                gtk::CheckButton{
                label: format!("Item{}",i),
                clicked => ConfigMsg::ToggleEnhance,
                active: true,
                }
            })},
        },
    }
}
```

Or do I have to rewrite the view using `append` and loop from there?

**Comment by antoyo** [comment]
That's unfortunately not possible, but there are helper functions:
[look at this example](https://github.com/antoyo/relm/blob/master/examples/widget-list.rs#L113).

**Comment by ivanceras** [comment]
Thanks, I think that will suffice.
