### ISSUE TITLE
Handling resizing widgets with DrawHandler<DrawingArea>

### ISSUE THREAD

**Issue by xd009642** [antoyo/relm#153]
I'm trying to use a `DrawHandler<DrawingArea>` and while the example is a starting point I'm not quite sure how to get the width/height of the `DrawingArea` from the `DrawHandler`. As the widget is cloned when constructing the `DrawHandler` I can't keep my old instance of it around and use `get_allocated_{width|height}` and I can't see a clear way to go from the `cairo::Context` back to something that implements `WidgetExt`?

I'm a bit of a relm beginner so I'm aware I may just be missing something rather simple. But it might also be worth updating the docs or examples to make usages like this clearer as well.

**Comment by antoyo** [comment]
Well, you get a message when it's time to draw, so you can just access the widget by the name you give it [here](https://github.com/antoyo/relm/blob/master/examples/drawing.rs#L163) and use it like [here](https://github.com/antoyo/relm/blob/master/examples/drawing.rs#L120).

By the way, the drawing framework of relm [is buggy and experimental](https://github.com/antoyo/relm/issues/129), so use at your own risk.

**Comment by xd009642** [comment]
Ah I get it. And yeah I saw the drawing framework is buggy but I need to replicate some of the functionality of Qts QGraphicsScene and wanted to do the project in Rust not C++. 

As a follow up question, I don't suppose there's a way to add a scrollbar to a DrawingArea so you can have a larger canvas than the area allocated to the widget? I'm assuming the answer is no.

Also feel free to close this issue if you want. As far as I'm concerned, the issue is resolved :+1:

**Comment by antoyo** [comment]
I think you can add your DrawingArea into a [Scrollbar](http://gtk-rs.org/docs/gtk/struct.Scrollbar.html).

**Comment by xd009642** [comment]
Awesome thank you!
