### ISSUE TITLE
Provide ability to set properties with multiple values

### ISSUE THREAD

**Issue by asonix** [antoyo/relm#172]
For example, GTK's `set_wm_class` method takes two arguments, but there's currently no way to utilize this with the `view!` macro. Maybe this could be implemented by parsing tuples. into distinct arguments, like

```
gtk::ApplicationWindow {
    wmclass: ("my-app", "My App"),
}
```

If people actually need a tuple, they can do
```
gtk::ApplicationWindow {
    some_property: (("My", "Tuple")),
}
```

**Comment by antoyo** [comment]
Duplicate of #59.
