### ISSUE TITLE
Connect within update

### ISSUE THREAD

**Issue by balping** [antoyo/relm#179]
Hi,

I'm creating widgets dynamically, by reacting to events, inside the `update()` method. I'd like to add event listeners to the newly created widgets.

How could I use the `connect!` macro there? I don't seem to have access to the `relm` object there, just `self`.

**Comment by antoyo** [comment]
You need to save the `relm` object in your widget in the `model()` method, as done [here](https://github.com/antoyo/relm/blob/master/relm-examples/examples/http/src/main.rs#L106).
Then, you'll have access to it in the `update()` method via `self.model.relm`.

**Comment by balping** [comment]
Ah, thank you. I tried this, by saving a reference, but that didn't work – and I didn't think of `clone()`. Thanks again.
