### ISSUE TITLE
Use 7GUIs examples for consistent gui comparison + Better documentation

### ISSUE THREAD

**Issue by MathiasKandelborg** [antoyo/relm#183]
Hi! Thank you for your hard work on this project. I'd love to help with making it more approachable for outsiders. Where I'd like to see changes first, is in the initial documentation explaining the framework(why it exists, how it makes things good, etc.) and comments in the examples.

The website https://eugenkiss.github.io/7guis/ is great when making a GUI framework. At the very least, the 7 examples in there would be great to have. At the very most, writing some documentation in regards to the current dimensions of evaluation, would be very helpful for people choosing a GUI framework, and provide a solid foundation for people wanting to contribute(explaining how and what relm does, and why, makes it easy to consider contributing or finding another project).

On a side note, I'd like to note how I'm unsure if everything done with relm can be done with the `view!` macro. I've tried to make a tree-view and couldn't figure how to initialize the model with the view! macro. My point being that some explanation of what the `view!` macro actually is and what it inhibits would be great. Personally, I like the 'standard' method more, as it's easier to modulate the structure and handle the components/widgets.

**Comment by antoyo** [comment]
For your question about the `view!` macro: it should be possible to do everything you can do without, thought the support for doing it declaratively might not be done yet.
For instance, you can mostly do anything you want by adding [the `init_view()` method as in this example](https://github.com/antoyo/relm/blob/51be1a2423a6e86b90eee26ca0ddf6366ff409ee/relm-examples/tests/child-event.rs#L45-L50), which allow you do to things the `gtk-rs` way while still using the `relm` way for the rest.

I'm not exactly sure what you're asking me here.
Do you want to contribute by making these examples?
Some of the first examples are already there in some form (or they're close to these).
But it would be great to have these kinds of example indeed.
Thanks for the suggestion.

**Comment by antoyo** [comment]
Fixed by #282.
