### ISSUE TITLE
How to access to a relm::Widget?

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#193]
In relm 0.9, the method `relm::Component::widget()` returns the `relm::Widget` but since 0.10 it returns `relm::Widget::Root`. Is there another way to interact with `relm::Widget` in a parent widget?

**Comment by antoyo** [comment]
I'm not sure I understand your problem: `Component::widget()` is still [there](https://github.com/antoyo/relm/blob/master/src/component.rs#L74).
There's also a [`Widget::root()` method](https://github.com/antoyo/relm/blob/master/src/widget.rs#L58).

**Comment by sanpii** [comment]
Yes but in 0.9 it returns `WIDGET` and `WIDGET::Root` in 0.10: https://github.com/antoyo/relm/compare/0.9.0...0.10.0#diff-852c8250af37b95ed01ce8c7dc82e312L71-R67

```diff
-    /// Get the widget of this component.
-    pub fn widget(&self) -> &WIDGET {
-        &self.0.widget
+    /// Get the widget of the component.
+    pub fn widget(&self) -> &WIDGET::Root {
+        &self.widget
```

**Comment by antoyo** [comment]
Oh, that was unsound.
In relm, there's only one owner to a widget.
The way to "access" a child widget is through [communication](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication-attribute.rs).

**Comment by sanpii** [comment]
Ok, I definitively need to rethink my application. Thank you.
