### ISSUE TITLE
Application design question

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#21]
Hello,

I try to develop an application with a strong model/view segregation. The frontend sends a signal and the `Application` struct react to its and launches the corresponding backend method. Something like that:

```rust
struct Application {
    frontend: ::relm::Component<Window>,
    backend: Backend,
}

impl Application {
    pub fn new(backend: Backend) -> Self {
        Application {
            frontend: ::relm::init().unwrap(),
            backend: backend,
        }
    }

    pub fn run(&self) {
        self.frontend.widget.show_all();
        ::gtk::main();
    }

    fn update(&self, event: Msg)
        match event {
            Msg::Start => self.backend.start(),
        };
    }
}
```

This example doesn’t works because `relm::init` is private and I don’t know how can I plug the `update` method.

**Comment by antoyo** [comment]
I started to add a way to create a `relm` `Widget` where its root element is another `relm` `Widget` which will require an exported (`pub`) way to create a `relm` `Widget`.
I believe this will fix this issue.

**Comment by antoyo** [comment]
There's now a `create_component()` function.
You can look at [this example](https://github.com/antoyo/relm/blob/master/examples/relm-root.rs#L140) to see how it's used.

For your issue with the `update()` method, I wonder why you don't implement the `Widget` trait.
This method is in the `Widget` trait, so that can make sense to implement it as `relm` is working with this trait.

**Comment by sanpii** [comment]
> I wonder why you don't implement the `Widget` trait.

Because I did’t find how can I pass an external dependancy. The `Backend` struct is built from command line arguments, I can’t create it in the `model()` method.

**Comment by antoyo** [comment]
If there was a way to populate the `Model` from a parameter, would this fix your issue?

I'll probably need to add such a feature for `mg` as there's something build from a file, which is a similar issue, I believe.

**Comment by sanpii** [comment]
> If there was a way to populate the `Model` from a parameter, would this fix your issue?

Yes.

**Comment by antoyo** [comment]
I added the ability to specify a model parameter.
You can look at one of the [model-param examples](https://github.com/antoyo/relm/blob/master/examples/model-param-attribute.rs).
I'll soon release a version so that you don't have to rely on the master branch.

**Comment by sanpii** [comment]
Great job, that also works with children widgets via the `add_widget` method.

Thank you 😄
