### ISSUE TITLE
How to set application-wide css stylesheet

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#213]
In the GTK+, [they do it](https://github.com/gtk-rs/examples/blob/master/src/bin/css.rs) by directly applying it to an application, but in Relm, you don't use the `Application`, but you call `run` method on your `Widget`.

Is there a way to get the application directly or to set the stylesheet on a widget.

**Comment by MGlolenstine** [comment]
Ok, found [this](https://github.com/sanpii/effitask/blob/master/src/application/widget.rs#L82).

An example of this would be nice, so I might push a pull request for it.

**Comment by antoyo** [comment]
Nothing prevents you from using Application with relm.
