### ISSUE TITLE
How to close a widget

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#214]
I have a class `Popup`, that opens a popup, which has a `gtk::Window(gtk::WindowType::Popup)` for a parent. But whenever I run it using 
```Rust
#[allow(unused)]
fn show_modal(pt: PopupType){
    Popup::run(pt);
}
```
it never stops, or at least it never continues onward from that `Popup::run(pt);` line. Stuff after that line doesn't get executed and the function never returns.

I'm currently closing it like this
```Rust
let window = self.window.clone();
button1.connect_clicked(move |_c| {
    glib::clone!(@strong window => move || {
        cbf();
        window.close();
    })();
});
```
I'm not sure if that only closes the window and leaves other stuff running or if it closes everything.

What would the correct way to close a popup be in this case?

**Comment by antoyo** [comment]
That's normal because `run()` creates a new inner gtk+ event loop.
You should call `.destroy()` on your popup to end this, I believe.

**Comment by MGlolenstine** [comment]
Destroy still doesn't kill the event loop. The window does close, but with the same problem as above.

**Comment by antoyo** [comment]
The [doc](https://developer.gnome.org/gtk3/stable/GtkDialog.html#gtk-dialog-run) says to either destroy or send a response. Maybe try to send a response.
Or maybe ask the gtk+ people. I don't remember how that works.

**Comment by MGlolenstine** [comment]
Ok, thanks for your help!

**Comment by MGlolenstine** [comment]
`gtk::main_quit();` did the trick!
Thanks!

**Comment by MGlolenstine** [comment]
```
    window.destroy();
    gtk::main_quit();
``` 
Did the trick!

Thanks!
