### ISSUE TITLE
How to send Message to a child

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#216]
This is a continuation of #204 ...
Now I have everything set up for the ListView, but I'm having some problems adding to the said list.
It works fine to add it to the constructor, but if I make a public method `add_entry`, I can't call it, as I get `relm::component::Component<ListView>` instead of just `ListView`, that is when I get it like this
```Rust
#[name="list"]
ListView(vec![]){
},
fn update(&mut self, event: ListMsg){
    self.list;
}
```

Now I tried adding an entry using this 
```Rust
fn add_entry(&mut self, item: String){
    self.model.values.push(item);
}
```
but I can't call it.

How can I send a message or call a method inside a component?

PS: If I understand [this](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication-attribute.rs#L165) correctly, [when the button](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication-attribute.rs#L162) is clicked, it sends a message to the child, in this case, `counter1`. How would I do that via code?

**Comment by antoyo** [comment]
For every `*-attribute.rs` example, there's [one without using the `#[widget]` attribute](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication.rs#L265).

**Comment by antoyo** [comment]
Do you need more help or can we close this issue?

**Comment by MGlolenstine** [comment]
I think we can close it, I haven't gotten around to testing it, but I'll reopen, if more questions arise.

Thanks!

**Comment by MGlolenstine** [comment]
I just came around to testing it, and it works well with the `emit()`.

Thanks!
