### ISSUE TITLE
Unable to init server: Could not connect: Connection refused thread 'main' panicked at 'Win::run failed: ()'

### ISSUE THREAD

**Issue by nlam1170** [antoyo/relm#230]
Got this error message while running the `button.rs` in `relm/relm-examples/examples.` I have GTK and the relevant relm crates installed. However, I am running in Ubuntu WSL2 , which I suspect is the reason for this error. Could anyone confirm or give some other possible reasons for failure. Thank you!

**Comment by antoyo** [comment]
Are you able to use gtk-rs directly (without relm)?

**Comment by nlam1170** [comment]
> 
> 
> Are you able to use gtk-rs directly (without relm)?

So I tried running just pure gtk-rs code and it still throws a similar error, so I guess its not a relm fault directly. I tried some of the troubleshooting help on google(mostly this one https://askubuntu.com/questions/614387/gksu-gtk-warning-cannot-open-display-0), but couldn't get it to work. Do you know any other possible solutions? Otherwise I might just have to move over to normal windows for this one. Thank you

**Comment by antoyo** [comment]
I suggest you ask on gtk-rs channel as I have never used WSL.

**Comment by nlam1170** [comment]
> 
> 
> I suggest you ask on gtk-rs channel as I have never used WSL.

Alright sounds good. I'll close this issue then. Thanks
