### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by krupitskas** [antoyo/relm#232]
Hey!
I've just come up to the relm UI library and if it even use gtk3 behind (not a native rust UI toolkit), I like that at least I have lot of widgets out of the box. I know from linux experience that gtk can be highly customized. Can I customize my own gtk application and ship it to all 3 platforms?

**Comment by antoyo** [comment]
I'm not sure what you mean by customizing, by that seems to be a GTK+ question, not a relm-specific question, so please ask on the appropriate channel.

An example of how to style CSS (if it's what you want) is [here](https://github.com/antoyo/mg/blob/36589c1b1bfdcc2ee3d5afc4093f096c118d95c9/src/app/status_bar.rs#L85-L88).
