### ISSUE TITLE
3D rendering / wgpu particularly

### ISSUE THREAD

**Issue by krupitskas** [antoyo/relm#233]
Hey! Simple question, how can use wgpu to render 3D stuff into the gtk predefined area?

**Comment by antoyo** [comment]
This seems to be a gtk+ related question, not a relm-specific question, so please ask on the appropriate channel.

I don't know about `wgpu`, but an example of integrating 3d stuff in gtk-rs can be found [here](https://github.com/antoyo/servo-gtk/blob/master/src/view.rs#L151).
