### ISSUE TITLE
Hot code reload / code swap on runtime

### ISSUE THREAD

**Issue by charafau** [antoyo/relm#236]
Hi, I really like the way this project is going I think gtk need declarative framework like this. One great improvement would be hot code reload, which would help for rapid development.

**Comment by antoyo** [comment]
That would be really hard. I don't think the implementation complexity outweights the benefits.

**Comment by zzeroo** [comment]
@charafau Dit you know [`cargo-watch`](https://github.com/passcod/cargo-watch)

I use often commands like these:
```bash
cargo watch -x build
```

but you could also pass the `run` command so each time you save your file, cargo builds and runs it for you. This works very well in gtk-rs land and with relm of course, too.
```bash
cargo watch -x run
# this is also possible
cargo watch -x run --feature "foo" 
cargo watch -x "run --example bar"
```

**Comment by charafau** [comment]
@zzeroo thank you for your comment. I very casual rust developer so didn't know about this one. Will give it a go! Thanks 🙇🙏
