### ISSUE TITLE
Separation between GUI and logic

### ISSUE THREAD

**Issue by paulolieuthier** [antoyo/relm#237]
How would you go about separating GUI from application logic? I'm trying to use channels but I'm having a hard time. It would be nice to see an example like a simple chat application with a separate modules for storing messages, configuration etc.

**Comment by antoyo** [comment]
(Sorry for the late reply.)

I'm not sure exactly what you mean by separating GUI from application logic as the `update()` method is the application logic and the `view!` macro is the GUI, so they are already separated.

If you want to know how to better organize your application, I suggest you create multiple relm widgets and send messages between them. See the [`communication` example](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication-attribute.rs) for an example of how to do that.

**Comment by paulolieuthier** [comment]
Hey, don't worry! I really enjoyed the project.

I mean separating into different modules in a way that the core module would not depend on relm or even gtk. Channels could be used to communicate events in a frontend-agnostic way.

**Comment by antoyo** [comment]
You can still use the same way as in the communication example, sending messages using a handle to a widget.

If you want to send a message from another thread, there's a `Channel` in relm. See [this example](https://github.com/antoyo/relm/blob/master/relm-examples/examples/multithread.rs) for usage.

**Comment by paulolieuthier** [comment]
I saw the examples and relm's `Channel`, but still struggled. I will revisit it soon and create more specific issues if needed.

**Comment by paulolieuthier** [comment]
A more elaborate example would still be nice. :smile:

**Comment by antoyo** [comment]
Yep. There's already [an issue](https://github.com/antoyo/relm/issues/11) for that ;) .
