### ISSUE TITLE
relm-derive macro generate codes that cargo clippy flags

### ISSUE THREAD

**Issue by emmanueltouzery** [antoyo/relm#238]
recent `cargo clippy` has started to flag code generated by the relm-derive macro. I think the error is self-explanatory:

```rust
warning: redundant field names in struct initialization
   --> src/widgets/wintitlebar.rs:263:20
    |
263 |             #[name="main_window_stack_switcher"]
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `main_window_stack_switcher`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_name
```

The lint is https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_name

It's about field puning: 

```rust
let foo = Foo { bar: bar };
// should be
let foo = Foo { bar };
```

I guess relm-derive could either generate code that clippy likes, or worst-case generate locally for that code an ignore annotation for clippy.

**Comment by antoyo** [comment]
Yeah, there's a PR #234 already to workaround this.
I haven't had the time to look at that yet.
I look at it soon.
