### ISSUE TITLE
Treeview with editable checkboxes beside items?

### ISSUE THREAD

**Issue by raphtlw** [antoyo/relm#241]
How can I create a treeview with editable checkboxes beside items using the widget attribute?

**Comment by antoyo** [comment]
Currently, there's no declarative way to create a complete treeview.
The best you can do is [this](https://github.com/antoyo/relm/blob/master/relm-examples/tests/child-event.rs#L120-L122) and use a `gtk::CellRendererToggle` [here](https://github.com/antoyo/relm/blob/master/relm-examples/tests/child-event.rs#L95).

**Comment by raphtlw** [comment]
@antoyo thanks for the reply, i tried using CellRendererToggle but i couldn't toggle the thing and the text wasn't shown in the treeview. i'll just switch to the other way to build the widget tree :+1:
