### ISSUE TITLE
Gtk4 in future

### ISSUE THREAD

**Issue by ondra05** [antoyo/relm#256]
Now, when gtk4 is released and there is gtk4-rs in development, it would be nice to have relm for gtk4-rs in future, when gtk4-rs will be production-ready.

**Comment by antoyo** [comment]
How do you suggest I do this?

Should there be a `relm-gtk4` crate?
Should it be a feature flag?

**Comment by ondra05** [comment]
> How do you suggest I do this?
> 
> Should there be a `relm-gtk4` crate?
> Should it be a feature flag?

I thought about copy this repo as relm and keep gtk3 as relm-gtk3 but that would break compatibility, So I suggest relm4.
