### ISSUE TITLE
Why fragile crate is copy in src/vendor?

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#270]
[src/vendor/fragile](https://github.com/antoyo/relm/tree/master/src/vendor/fragile) VS [fragile](https://crates.io/crates/fragile)

**Comment by antoyo** [comment]
That was a poor attempt to reduce the number of dependencies.
We should just remove the vendored version and use the version on crates.io.

**Comment by sanpii** [comment]
This is very usefull to fix #239 :smile:
