### ISSUE TITLE
Create a new instance of a Relm widget

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#288]
How does one create a new instance of a Relm widget?
If I want to add GTK widgets to a `FlowBox`, we'd do it from inside the `init_view` and just use `gtk::Container::add()`, but I'm unsure on how to do it with Relm widgets, as they don't seem to have `new()` method and the only method that returns the widget itself is `view`, which requires `Relm<WidgetModel>`.

Is there a better way to do this, maybe just linking a vector to the `FlowBox`?

**Comment by MGlolenstine** [comment]
I've solved the problem. You can use `relm::create_component`, provide arguments for the `model` method and just call `widget()` on it to get the widget you're looking for.
```Rust
                    let item_card = relm::create_component::<ItemCard>(d);
                    let item_card = item_card.widget();
                    self.widgets.search_result_box.add(item_card);
```

**Comment by antoyo** [comment]
You can also import the trait `ContainerWidget` and call the method [`add_widget()`](https://github.com/antoyo/relm/blob/master/src/container.rs#L137).
