### ISSUE TITLE
Add a list of applications using relm

### ISSUE THREAD

**Issue by antoyo** [antoyo/relm#30]
https://github.com/sanpii/yellow-pitaya

**Comment by juchiast** [comment]
https://github.com/juchiast/gameoflife
Re-writed from dhad05/GoL

**Comment by antoyo** [comment]
Thanks, I'll add it to the list too.
Any reason of not using the `#[widget]` attribute?

**Comment by antoyo** [comment]
@sebasmagri: May I add your [rusty-sounds project](https://github.com/sebasmagri/rusty-sounds) to this list?
As you can see, relm evolved a lot since the HackFest :) .

**Comment by sebasmagri** [comment]
Sure thing @antoyo... It's a little bit outdated then, but I can update it this weekend probably.

**Comment by etrombly** [comment]
Still in work, and it's a basic example, but you can add https://github.com/etrombly/country_parser

**Comment by juchiast** [comment]
Hello, I found a very interesting crate using relm: https://github.com/niklasf/rust-chessground

**Comment by antoyo** [comment]
@juchiast Thanks, I added it.

**Comment by sanpii** [comment]
https://github.com/sanpii/effitask

**Comment by antoyo** [comment]
Thank you @sanpii.
I close this issue:
from now on, please open a pull request to include your project.
