### ISSUE TITLE
Dynamically create new widgets

### ISSUE THREAD

**Issue by Jkillelea** [antoyo/relm#302]
Hi there,

I'm trying to create a list of widgets, which are dynamically created in response to user actions. It doesn't seem like there's a way to create widgets on the fly, is there?

Ideally, I'd like to be able to do something like:
```
list_box.append(Widget::new())
```

I know that `relm::create_component<T>` exists, but it's difficult to use in the above context, as `list_box` above accepts a reference to the created component/widget, but the owning handle goes out of scope quickly, while the `list_box` hangs around much longer.

**Comment by antoyo** [comment]
Hi!
Are the `add_widget()` and `remove_widget()` functions that you can see in this [example](https://github.com/antoyo/relm/blob/master/relm-examples/examples/widget-list.rs#L115-L121) insufficient?

**Comment by Jkillelea** [comment]
Thanks, I didn't see that method, and I didn't know about the `ContainerWidget` trait.
