### ISSUE TITLE
How to trigger an update without user interaction?

### ISSUE THREAD

**Issue by bistace** [antoyo/relm#312]
Hello,
I am trying to create a chess engine that will be used to train an AI to play chess against other engines. I am trying to use relm to display the state of the board. 

Here's what I did so far:
  - create an empty board struct and pass it to the model
  - display an empty board in the main window

I have some difficulties seeing how to mutate the board and trigger an update without the user interacting with the window (there is no button or anything, it is just used to display the state of the board). I have looked at components and workers but it seems that they still need an input message to trigger some actions.

Could you please point me in the right direction?

**Comment by antoyo** [comment]
Hi.
I guess the engine will run in another thread, right?
If that's the case, you could use a `Channel` for inter-thread communication: https://github.com/antoyo/relm/blob/master/relm-examples/examples/multithread.rs#L53-L62

It provides a `send()` method that you can use whenever your engine has a new move to play and the `Channel` callback can be use to [send a message to the chessboard widget](https://github.com/antoyo/relm/blob/master/relm-examples/examples/multithread.rs#L56).

**Comment by bistace** [comment]
Thank you for the fast reply and pointers, I will look into it!
