### ISSUE TITLE
Think about how to avoid having to write wrapper methods for gtk properties of relm widget

### ISSUE THREAD

**Issue by antoyo** [antoyo/relm#35]
For instance, the following:
```rust
View {
    visible: self.model.visible,
}
```
requires to write a `set_visible()` method calling the `set_visible()` method from gtk.

Might be possible by calling `Widget::root()`.

**Comment by sanpii** [comment]
Now that works like that.

**Comment by antoyo** [comment]
No. What this issue means is that if I have a `View` relm widget and I want to set one of its gtk properties, I need to do something like:
```rust
// Using the relm widget.
view! {
    View {
        Visible: self.model.visible,
    }
}

// Defining the relm widget.
fn update(&mut self, event: Msg) {
    match event {
        Visible(visible): self.gtk_widget.set_visible(visible),
    }
}
```

Instead, I'd like to avoid having to write the wrapper and be able to do something like this (syntax to be determined):
```rust
view! {
    View {
        gtk@visible: self.model.visible,
    }
}
```

**Comment by sanpii** [comment]
This code works: https://github.com/yellow-pitaya/frontend/blob/master/src/application/generator/output.rs#L104-L107

Setting `label` calls the `root.set_label()` method.

It could be nice to have the choice between calling the method on the root (with `gtk@` prefix seems good) or on the `relm::Widget`. Currently I need to define a setter signal :disappointed:

**Comment by antoyo** [comment]
Oh, you're right: it works already.
So why would you need the `gtk@` prefix for?
We can already bind a signal with the following syntax:
```rust
view! {
    View {
        Visible: self.model.visible,
    }
}
```
This will send the event `Visible(self.model.visible)` whenever the `visible` attribute is updated.

**Comment by sanpii** [comment]
Properties and events are not for the same thing. For me it’s unnecerary to create a signal for configuring a widget (setting a static label for example).

**Comment by antoyo** [comment]
I don't understand what is missing according to you.
It's possible to bind a gtk property like this:
```rust
view! {
    View {
        visible: self.model.visible,
    }
}
```
And it's possible to bind a message like this:
```rust
view! {
    View {
        Visible: self.model.visible,
    }
}
```
(The difference is the capital letter `v` vs `V`.)
What would you like to be able to do?

**Comment by sanpii** [comment]
Yes that work’s for gtk widgets, but only events work with relm widgets. I would like properties for relm widget (not just a passthought to the root widget).

**Comment by antoyo** [comment]
In this example, `View` is a relm widget.
Properties for relm widget, as you say, is simulated by sending the `Visible` message to the `update()` method of the `View` relm widget.
Isn't that enough?

**Comment by sanpii** [comment]
That doesn’t work for me: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc2ec702fb9379cc095b75bc646f2f72

```
error[E0599]: no method named `set_label` found for type `&gtk::auto::box_::Box` in the current scope
  --> examples/test.rs:52:17
   |
52 |                 label: "test".to_string(),
   |                 ^^^^^ method not found in `&gtk::auto::box_::Box`
   |
   = note: the method `set_label` exists but the following trait bounds were not satisfied:
           `&gtk::auto::box_::Box : gtk::auto::label::LabelExt`
           `gtk::auto::box_::Box : gtk::auto::label::LabelExt`
```

```
#[derive(relm_derive::Property)]
enum Property {
    label: String,
}

widget.set_property();

**Comment by sanpii** [comment]
It would be nice to have a separate logic to reduce number of events and the size of the `update` method (this part can be automatically generated):

```rust
#[derive(relm_derive::Property)]
enum Property {
    Label(String),
}

#[relm_derive::widget]
impl Widget for Box {
    // It’s probably not the best way to glue widget and property…
    type property = Property;

    fn model() -> String {
        String::new()
    }

    fn update(&mut self, _event: ()) {
    }

    view! {
        gtk::Box {
            gtk::Label {
                text: self.model,
            },
        }
    }

    fn set_label(&mut self, label: String) {
        self.model = label;
    }

    fn get_label(&self) -> String {
        self.model
    }
}
```

The new generated method via `relm_derive::widget`:
```rust
fn properties(&mut self, event: PropertiesMsg) {
    match event {
        PropertiesMsg::SetLabel(label) => self.set_label(label),
        // I don’t know how to return something here…
        PropertiesMsg::GetLabel(label) => self.get_label(),
    }
}
```

And new methods, like `emit`:

```rust
widget.set_property(Property::Label, String::new());
let label = widget.get_property(Property::Label);
```

**Comment by antoyo** [comment]
You need a capital `L` in `Label`. This works:
```rust
extern crate relm;
extern crate gtk;

use gtk::{
    LabelExt,
    WidgetExt,
};
use relm::Widget;

#[derive(relm_derive::Msg)]
pub enum BoxMsg {
    Label(String),
}

pub struct Model {
    label: String,
}

#[relm_derive::widget]
impl Widget for Box {
    fn model() -> Model {
        Model {
            label: String::new(),
        }
    }

    fn update(&mut self, event: BoxMsg) {
        match event {
            BoxMsg::Label(label) => self.model.label = label,
        }
    }

    view! {
        gtk::Box {
            gtk::Label {
                text: &self.model.label,
            },
        }
    }
}

#[derive(relm_derive::Msg)]
pub enum Msg {
    Quit,
}

use BoxMsg::Label;

#[relm_derive::widget]
impl Widget for Win {
    fn model() -> () {
    }

    fn update(&mut self, event: Msg) {
        match event {
            Msg::Quit => gtk::main_quit(),
        }
    }

    view! {
        gtk::Window {
            #[name="vbox"]
            Box {
                Label: "test".to_string(),
            },
            delete_event(_, _) => (Msg::Quit, gtk::Inhibit(false)),
        }
    }
}

fn main() {
    Win::run(()).expect("Win::run failed");
}
```

**Comment by antoyo** [comment]
For your other idea, generating getter seems complicated because it would work via message passing because the model is owned by relm itself.
For the size of the `update()` method, I already thought it could be huge indeed and thought about an idea that I rejected.
I think the simplest is just to make this method a proxy to other methods in case some cases are too big.

**Comment by sanpii** [comment]
Thank you. It's already a good improvement for my code :smiley:

**Comment by antoyo** [comment]
I'm closing this issue.
Feel free to open another one if you think you can improve the ergonomy while keeping the code generator simple.
