### ISSUE TITLE
Question: how to update model from outside widget and update widget afterward?

### ISSUE THREAD

**Issue by Geobert** [antoyo/relm#37]
Hi,
I'm trying to write an app with Relm and I think I understand well the different examples but they all show the case when the model is created by the widget.

I have data read from the hard drive that I want to display and I'm wondering how to inject them in the widget and make the widget refresh

Thank you for any insight :)

**Comment by antoyo** [comment]
I'm not sure to understand exactly what you want to do.

You probably want to use [a model parameter](https://github.com/antoyo/relm/blob/master/examples/model-param-attribute.rs#L60) to send data to be used in the model.

If it is not enough, can you show me a code example of what you want, please?

**Comment by Geobert** [comment]
Oh, I missed this example, this is what I want indeed! Thanks!

**Comment by antoyo** [comment]
I'll move some examples into the tests folder so that there's less example and it will be easier to find something in them.
Actually, many examples are only there to tests relm.

**Comment by Geobert** [comment]
Is there any example for using ComboBox? I'm surfing around trying to find my way into feeding an enum into a ComboBox for some time now :(

**Comment by antoyo** [comment]
For now, relm does not help in managing the model of a GTK widget.
There's [an issue for that](https://github.com/antoyo/relm/issues/17), but I'm still not sure how to design this.

For now, you'll want to manage the GTK model yourself and use a method like [`new_with_model`](http://gtk-rs.org/docs/gtk/struct.ComboBox.html#method.new_with_model).

**Comment by Geobert** [comment]
So I create a fn view(…) instead of using view! macro?

**Comment by antoyo** [comment]
Oh, sorry, what I said was misleading.
You want to use [`set_model`](http://gtk-rs.org/docs/gtk/trait.ComboBoxExt.html#tymethod.set_model) instead so that you can continue using the `view! macro`.

**Comment by Geobert** [comment]
Ok, what I can't see is where shall I call set_model? in a "dummy" event so update() is called?

Thank you very much for your help!

**Comment by antoyo** [comment]
No problem.
So, what you could do is:
```rust
fn model() -> Model {
    Model {
        gtk_model: // create your GTK model here
    }
}

view! {
    gtk::ComboBox {
        model: &self.model.gtk_model,
    }
}
```
Another option would be to call `set_model()` in the `init_view()` method. See [this example](https://github.com/antoyo/relm/blob/49ca37deec56ed5aeb0f818d2dac6799501bd1a8/examples/simple.rs#L48) to see how this method is used.

**Comment by Geobert** [comment]
Thank you! 

Is there a better place than github for this kind of questions? So I don't flood your issue tracker with questions ^^

**Comment by antoyo** [comment]
I added a [gitter room](https://gitter.im/relm-rs/Lobby) for this project and I invited you into this rom.
I'll also add an IRC channel.

**Comment by Geobert** [comment]
I've seen that, thank you!
