### ISSUE TITLE
connect! syntax error

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#38]
Hello,

I would like to connect a signal to a widget and emit a signal for another.

If I understand correctly, this is the first form of the `connect!` macro.

I wrote:

```rust
connect!(acquire, acquire::Signal::Start(source), graph, graph::Signal::SourceStart(format!("{}", source)));
```

But that doesn’t compile:
```
error: no rules expected the token `,`
   --> src/application/mod.rs:225:64
    |
225 |         connect!(acquire, acquire::Signal::Start(source), graph, graph::Signal::SourceStart(format!("{}", source)));
    |                                                                ^
```

**Comment by antoyo** [comment]
These doesn't look like gtk signals, so you probably want to use the [latest form](https://github.com/antoyo/relm/blob/master/src/macros.rs#L96) of this macro (with the `@` sign).
See [this example](https://github.com/antoyo/relm/blob/master/examples/communication.rs#L236).

**Comment by sanpii** [comment]
Thank you, the following notation works fine:
```rust
connect!(acquire@acquire::Signal::Start(source), graph, graph::Signal::SourceStart(format!("{}", source)));
```
