### ISSUE TITLE
Support gtk::Gesture in view! macro

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#42]
`gtk::Gesture` is like an event box specialized in gesture events. Unfortunately they aren’t a container.

You can find a exemple in rust here: https://github.com/yellow-pitaya/frontend/blob/5ee4bb293f74ebb0f105c17984b001ec957b1a66/src/application/graph/level/widget.rs#L213

And more in C here: https://wiki.gnome.org/HowDoI/Gestures

**Comment by antoyo** [comment]
This is indeed insupported, right now.
For instance, the following code gives an error:
```rust
view! {
    gtk::Window {
        gtk::Box {
            orientation: Vertical,
            #[name="label"]
            gtk::Label {
                text: &self.model.counter.to_string(),
            },
            gtk::GestureDrag(&label) {
            },
        },
        delete_event(_, _) => (Quit, Inhibit(false)),
    }
}
```
I'll probably add a syntax like this:
```rust
view! {
    gtk::Window {
        gtk::Box {
            orientation: Vertical,
            #[name="label"]
            gtk::Label {
                text: &self.model.counter.to_string(),
            },
        },
        delete_event(_, _) => (Quit, Inhibit(false)),
    },
    gtk::GestureDrag(&label) {
    },
}
```

**Comment by antoyo** [comment]
That is now possible. See this [example](https://github.com/antoyo/relm/blob/master/relm-examples/examples/orphan-widgets-attribute.rs#L99-L103).
