### ISSUE TITLE
Passing messages upwards

### ISSUE THREAD

**Issue by superlou** [antoyo/relm#58]
I have been able to follow the examples with nested Relm widgets.  I am building the views by passing data downwards, in that the parent model has all of the data, and creates sub-models/sub-widgets to accomplish more and more specific GUI tasks, though the highest parent still owns all the model data.  

However, not all of the messages are handled inside a widget.  I'd like to pass messages upwards to their parents.  Is it possible to generate a message inside a widget that propagates upwards to the parent?  Then I can have the parent mutate the child data causing a view update.

This data-down/actions-up pattern was very helpful in the Ember.js world for composing complex interfaces.  If I'm way off base, and there's a more Rustic/Relmy way to approach this, let me know.

**Comment by antoyo** [comment]
This is already supported.
Please take a look at the [communication example](https://github.com/antoyo/relm/blob/master/examples/communication-attribute.rs).

[Here](https://github.com/antoyo/relm/blob/master/examples/communication-attribute.rs#L173), you can see how to listen to a child signal (and thus be able to modify the parent model when the child sends a message).

[And here](https://github.com/antoyo/relm/blob/master/examples/communication-attribute.rs#L172), you can see how to send a message to the child widget.

**Comment by superlou** [comment]
If I have a dynamic number of children, is there a way to address them with the attributes system, or do I switch to manually using `connect!`?

**Comment by antoyo** [comment]
Currently, there's no way to manage list of widgets with the `#[widget]` attribute.
You'll need to use `connect!` and you can find a communication example not using this attribute [here](https://github.com/antoyo/relm/blob/master/examples/communication.rs).

**Comment by superlou** [comment]
I've been playing around with that example, and I think I'm understanding how to pass messages upwards.  When the higher widget receives the signal, it mutates it's model which is a vector of the lower widgets' models.  I was hoping that I could then automatically update the lower widgets.  Maybe, what I'm looking for is instead of creating a new model when adding a widget, I'd rather pass a reference to the parent's data:

```
fn view relm: &RemoteRelm<self>, model: &ParentWidgetModel) -> Self {
    // hbox.add_widget::<SubModelWidget, _>(&relm, (arg1, arg2, arg3)); <-- not this
    hbox.add_widget::<SubModelWidget, _>(&relm, model.SubWidgetModel);
}
```

Since my Relm application is going to pretty much just be a GUI shell that is constantly sending/receiving model updates over HTTP, having a central source of models in the parent widget seemed convenient.  Messages from widgets ripple up to the topmost widget to get sent off to the backend, and backend responses update the models which ripple downwards into all of the widgets they affect.

Is this going to be a huge Relm antipattern, and is there a better way to do this?

**Comment by antoyo** [comment]
If I understand correctly your issues, you want to have multiple mutable references to your model (one in the parent and one in the child widget).
This is something we try to avoid in Rust and this is why [in the new branch](https://github.com/antoyo/relm/tree/feature/futures-glib) I made changes so that a model can only be changed from its widget.
The way you want to change the child widgets is throught message communication: to do so, you can either use the `connect!` macro, or directly calling `emit()` on a widget stream as you can see in [this crate](https://github.com/antoyo/mg/blob/ef968872319346c020b3838374a778bc98ff11e7/src/app/command.rs#L98).

**Comment by superlou** [comment]
I agree that makes sense.  I guess I was trying to figure out a way to pass the same model objects all the way up and down.   I think I need to separate my idea of the model into a serialized/serialized model from the backend, and a view model that Relm uses.  Thanks for the pointers!

**Comment by superlou** [comment]
@antoyo Sorry to bring this back to life.  So, since `connect!` and `emit()` are the recommended ways to mutate child widgets.  In Elm, I thought you could modify children by updating their model.  In Relm we send events up and down once the initial model is created?  I understand that there will be differences, just making sure my mental model is accurate.

**Comment by antoyo** [comment]
How do you modify a children model in `Elm`?
As far as I know, the only way to change the model is also in the `update` function.
