### ISSUE TITLE
Is it possible to add components during init_view?

### ISSUE THREAD

**Issue by superlou** [antoyo/relm#60]
I'm trying to create a [gtk::Grid](https://developer.gnome.org/gtk3/stable/GtkGrid.html) where the number of rows and columns are widget parameters.  During initialization, the grid is populated with the proper number and arrangement of another custom Relm widget.

I'm trying to use the `#[widget]` attribute as much as possible, since it makes the code a lot cleaner.  I was hoping to use `init_view` to populate the grid, but since it doesn't receive the `&Relm<PARENTWIDGET>` argument, is it too late in the lifecycle to create widgets?  Is there a better way?  I'm on Relm 0.10.0.

**Comment by antoyo** [comment]
It's never too late to add widgets, you can even add widgets in the `update()` method.
[The widgets can be assigned a name with the `#[name="widget_name"]` attribute.](https://github.com/antoyo/relm/blob/master/examples/child-event.rs#L125)
And this name is an attribute of `Self`, [so you can use it in `init_view()` (among other methods) to manipulate the view](https://github.com/antoyo/relm/blob/master/examples/child-event.rs#L61).
