### ISSUE TITLE
Emitting messages with parameters

### ISSUE THREAD

**Issue by superlou** [antoyo/relm#61]
Is it possible to emit a message on a child component with parameters?

**Comment by antoyo** [comment]
Yes. You do it the same way as you do without parameters.
[Here is one example.](https://github.com/antoyo/titanium/blob/64cd262e7650548e278bede71122e6ab1d5a337e/src/app/download.rs#L123)

**Comment by superlou** [comment]
:man_facepalming: 
Thanks!
