### ISSUE TITLE
Provide a prelude module

### ISSUE THREAD

**Issue by antoyo** [antoyo/relm#69]
To import all the `gtk::*Ext` traits that does not conflicts.

**Comment by zzeroo** [comment]
I would like to do that. Is that ok?
- [ ] create a prelude module
- [ ] include `gtk::*Ext` traits that do not cause a conflict
- [ ] update all examples/ documentation and include new prelude module

**Comment by antoyo** [comment]
Yes, that would be awesome.
You can just `use gtk::prelude::*` instead of manually finding out which traits have no conflicts.
Thanks a lot for your contributions.

**Comment by zzeroo** [comment]
Hi @antoyo, I need a decision.

I could just include `use gtk::prelude::*` everywhere (examples, README, ...) and fix the `use` statements, like so:
* https://github.com/antoyo/relm/pull/78/commits/2fbe0e580be5628b844408747c0da3cdd257dfb6

or, should we have a own prelude module like here:
* https://github.com/antoyo/relm/pull/78/commits/651bd7696780aea3a9e065782619e903487ce370

I mean the first version is very quick and shows that relm is very tight bound to gtk. The second example is more standard, and extenable. What do you think?

**Comment by antoyo** [comment]
The idea of using `gtk::prelude` directly is nice:
we don't need an additional prelude module for relm indeed.
I prefer to update the examples to use `gtk::prelude`.
Thanks for proposing this idea.

**Comment by antoyo** [comment]
@zzeroo I specified this issue for the milestone 1.0, so please tell me if you're still working on this issue and would like me to do it?
Thanks.

**Comment by antoyo** [comment]
Ok, since I'll rework all examples, I'll do it at the same time.

**Comment by antoyo** [comment]
I tried to do `use gtk::*;` but this was not working in some cases because different traits can have the same methods which causes ambiguity.
So, I'm closing as there's not much we can do, I think.
