### ISSUE TITLE
relm-attributes: widget macro - outdated docs / bug?

### ISSUE THREAD

**Issue by luc-tielen** [antoyo/relm#72]
Docs for relm_attributes 'widget' macro are confusing/outdated?
I tried example in README, but it doesn't work straight away.
I had to add some extra code myself to make it work, is this normal?
See my gist for example code: https://gist.github.com/luc-tielen/361e034d9363948ea36fb3c31da9476a

**Comment by antoyo** [comment]
Maybe it isn't clear, but the readme says to declare these types in the [`Usage`](https://github.com/antoyo/relm#usage) section (before the section about the `#[widget]` attribute).

**Comment by luc-tielen** [comment]
I see. Well my confusion was from the note below that example:

"The struct Win is now automatically created by the attribute, as are the function root() **and the types Model, ModelParam, Msg and Container**. You can still provide the method and the types if needed, but you cannot create the struct."

I will close this issue then, thanks for quick reply!

**Comment by antoyo** [comment]
Ok, I updated the readme to say associated types instead of only types.
Thanks for pointing that out.
