### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by luc-tielen** [antoyo/relm#73]
docs.rs and crates.io both have weird/buggy formatting

**Comment by antoyo** [comment]
For crates.io, I can't do anything.
They changed the purpose of [the issue I opened](https://github.com/rust-lang/crates.io/issues/995) and "fixed" it.

For docs.rs, can you tell me what's wrong?

**Comment by luc-tielen** [comment]
It's most likely related?

https://docs.rs/relm/0.10.1/relm/fn.run.html is an example of weird formatting.

**Comment by cars10** [comment]
Probably caused by the switch to markdown.

**Comment by zzeroo** [comment]
@luc-tielen Do you know even more incorrect text passages?

**Comment by luc-tielen** [comment]
@zzeroo just skimmed through most doc pages, also found:
- https://docs.rs/relm/0.10.1/relm/fn.init_test.html

Rest looks fine I think.

If I knew it was only a small fix I could've done them myself, or will you fix remaining?

**Comment by zzeroo** [comment]
@luc-tielen I've the tools up and running so I was so free to make the PR. Thank you for your contributions.

**Comment by antoyo** [comment]
That was fixed by pr #75 and #76.
Thank you.
