### ISSUE TITLE
Support custom titlebars

### ISSUE THREAD

**Issue by remcokranenburg** [antoyo/relm#84]
In Glade, you can specify custom titlebars like so:
```xml
<interface>
  <!-- ... -->
  <object class="GtkApplicationWindow" id="myapp">
    <child>
      <object class="GtkBox">
        <!-- ... application 'body' ... -->
      </object>
    </child>
    <child type="titlebar">
      <object class="GtkHeaderBar">
        <!-- ... custom titlebar with HeaderBar ... -->
      </object>
    </child>
  </object>
</interface>
```
The relm alternative:
```rust
view! {
    #[name="window"]
    gtk::ApplicationWindow {
      gtk::Box {
        // ... application 'body' ...
      },
      #[name="titlebar"]
      gtk::HeaderBar {
        // ... custom titlebar with HeaderBar ...
      },
    }
  }
```
Making this work requires some custom glue:

```rust
  fn init_view(&mut self) {
    self.window.set_titlebar(&self.titlebar);
  }
```

But this spits out the following warnings:

> (.:11585): Gtk-WARNING **: Attempting to add a widget with type GtkHeaderBar to a GtkApplicationWindow, but as a GtkBin subclass a GtkApplicationWindow can only contain one widget at a time; it already contains a widget of type GtkBox
(.:11585): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window

Plus some other warnings that have to do with widgets that I didn't show here:
>*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
(.:11585): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -144 and height 17
(.:11585): Gtk-WARNING **: Negative content width -23 (allocation 1, extents 12x12) while allocating gadget (node label, owner GtkLabel)
(.:11585): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

Would be nice to properly support custom titlebars (such as HeaderBars), maybe with a `#[type="titlebar"]` attribute. Or is there already a proper way that I'm missing?

**Comment by asonix** [comment]
I've found a way to avoid this warning:

1. Define a `Header` Widget that creates a headerbar
2. Store it in the Model as `header: Component<Header>`
3. in `view!` use `titlebar: self.model.header.widget(),`

**Comment by atsjj** [comment]
> I've found a way to avoid this warning:
> 
> 1. Define a `Header` Widget that creates a headerbar
> 2. Store it in the Model as `header: Component<Header>`
> 3. in `view!` use `titlebar: self.model.header.widget(),`

I was playing around with this project and I figured out how to actually do what you suggested.

Would an example like what @asonix suggested be beneficial for the project @antoyo? I'd be happy to submit my code in a pull, but I figure I'd ask first!

**Comment by antoyo** [comment]
@atsjj: I guess that could be helpful until there's a better way to do it. Thanks for your proposition!

**Comment by antoyo** [comment]
That should be possible to do using [a nested `view!` macro](https://github.com/antoyo/relm/blob/master/relm-examples/examples/nested-view-attribute.rs#L184-L188) now.
