### ISSUE TITLE
Error when there's syntax after the widget

### ISSUE THREAD

**Issue by antoyo** [antoyo/relm#86]
Like:
```rust
view! {
    gtk::Window {
    },
    delete_event(_, _) => (Quit, Inhibit(false))
}
```

**Comment by zmitchell** [comment]
I can take this one. I haven't tested anything, but I'm pretty confident this is a result of only looking at `tokens[0]` [here](https://github.com/antoyo/relm/blob/e550fdd83773629b18c1d7d828768161b4edcc23/relm-gen-widget/src/lib.rs#L355). I can just check whether the length of `tokens` is greater than 1, and then respond accordingly.

**Comment by antoyo** [comment]
If you know `nom` and are interested in doing much more than that, here's an idea that will also fix the issue #27:
I've learned recently that we can parse the syntax with (a version of) `nom` [by implementing the `Synom` trait](https://github.com/dtolnay/syn/blob/461d98ee7c6a61d5ee07f9d06fde8e07eff6bc4a/src/mac.rs#L74).
I guess that this would make the resulting parser way easier and more maintainable than the current manual one and will also fix the position of the error messages.

But if you only prefer to fix this issue, that's also fine. Fixing the whole thing is a lot more work :) .
Thank you.

**Comment by zmitchell** [comment]
I’ve never used `nom`, but I just did some reading and I think I can do that. I’ll fix this issue and https://github.com/antoyo/relm/issues/67, which I think is also caused by the same problem with `tokens`, then start on parsing with `nom`.

**Comment by antoyo** [comment]
If you need any help, I can answer your questions.
Thanks for your help.
