### ISSUE TITLE
How relm works?

### ISSUE THREAD

**Issue by amirouche** [antoyo/relm#87]
- Are you using the equivalent of a virtual-dom?
- Where is implemented the diff+patch / reconciliation algorithm?

TIA

**Comment by antoyo** [comment]
No, it doesn't use virtual-dom.
The macro will actually modify the `update()` method to insert the calls to gtk `set_property()` whenever a model attribute is assigned (either with `=` or with an operator like `+=`).
This means that the following code won't trigger a view update:
```rust
self.model.string.push_str("test");
```
while the following will:
```rust
self.model.string += "test";
```

**Comment by amirouche** [comment]
Ok. But when the view is called, what happens? Isn't the current scene graph patched with the new view?

**Comment by antoyo** [comment]
There's a similar code generation for when the view is created so that it gets the initial state.
