### ISSUE TITLE
parse() Widget: ParseError(None)

### ISSUE THREAD

**Issue by sanpii** [antoyo/relm#91]
I tried to update relm to 0.12 but I have an error:

```
   Compiling effitask v0.1.0 (file:///home/sanpi/projects/rust/effitask)
thread 'rustc' panicked at 'parse() Widget: ParseError(None)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: custom attribute panicked
   --> src/edit.rs:137:1
    |
137 | #[widget]
    | ^^^^^^^^^
    |
    = help: message: parse() Widget: ParseError(None)

error: Could not compile `effitask`.

To learn more, run the command again with --verbose.
```

https://github.com/sanpii/effitask/blob/master/src/edit.rs#L137

**Comment by antoyo** [comment]
I think you found a bug in the new parser because I can't find an mistake at first glance.
Let me some time to check what's wrong.
Also, I need to improve the error messages of the parser.

**Comment by antoyo** [comment]
Oh, I see, you're actually using a syntax that was never intended to be working :) .
[This line](https://github.com/sanpii/effitask/blob/master/src/edit.rs#L222) should not contain the prefix.
It should be:
```rust
Calendar("Created".to_owned()),
```
I'm actually surprised this syntax used to work.

So the rule is that qualified path (`module::Widget`) are for gtk widgets and unqualified path (`Widget`) are for relm widget.

**Comment by sanpii** [comment]
Thank you.
